import gitGet from "@/lib/axiosConfig";
import { useEffect, useState } from "react";

import Contact from "@/components/Contact";
import Navbar from "@/components/Navbar";
import Head from "next/head";

const DataAnalysis = () => {
        const [projects, setProjects] = useState([]);
        const [error, setError] = useState("")
    
        useEffect(() => {
            (async () => {
                try {
                    const res = await gitGet("/repos")
                    console.log(res)
                    setProjects(res)
                } catch (error) {
                    setError(error)
                }
            })();
    
        }, [])
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <main>
                <>
                    {error && <p className="alert alert-danger">{error}</p>}

                    {projects &&
                        <ul>
                            {projects.map(({ name, id }) => (
                                <li key={id}>{name}</li>
                            ))}
                        </ul>
                    }
                </>
            </main>

            <footer>
                <Contact />
            </footer>
        </>
    )
};

export default DataAnalysis;