import Head from "next/head";

import About from "@/components/About";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import Navbar from "@/components/Navbar";
import { useRouter } from "next/router";


export default function Home() {

  const router = useRouter()
  return (
    <>
      <Head>
        <title>Porfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        {/* 👇 Hero Hook */}
        <section
          className="d-flex align-items-center justify-content-center text-center p-5 bg-dark"
          style={{
            minHeight: "80vh",
            color: "#FEDCC3", // Soft highlight
          }}
        >
          <div>
            <h1 style={{ fontSize: "3rem", fontWeight: "bold", color: "#FAFEF7" }}>
              I build digital experiences <br />
              that people <span style={{ color: "#811D45" }}>*want*</span> to use — and keep using.
            </h1>
            <p style={{ fontSize: "1.5rem", marginTop: "1.5rem", color: "#9FBBC3" }}>
              I&apos;m a software developer passionate about helping businesses, brands, and creators
              bring their services online in a way that&apos;s elegant, engaging, and efficient.
            </p>
          </div>
        </section>

        {/* Main Site Content */}
          <Skills />
          
          <About />

          <Projects />
      </main>


      <Contact />
    </>
  );
}
